### ISSUE TITLE
[Error] Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by navigator8** [oschettler/knowfox#6] opened 2017-07-28 12:27 UTC
This error occurs under the following use cases:
1. Edit Concept
2. Change the  any of the fields under the bottom tabs
3. Press [Save Changes]

Result:

Whoops, looks like something went wrong.

**Comment by nhau** [comment] 2017-10-08 01:36
Whoops, looks like something went wrong.

This error keeps coming after most operation on th web. Kindly give this attention

**Comment by oschettler** [comment] 2017-10-08 21:00
With today's upgrade to Laravel 5.5, I have also added some better error handling. 

Could you please, when it happens again, note the time here so I can drill down into the logs. 

Thank you. 
-- Olav

**Comment by nhau** [comment] 2017-10-10 10:41
Here is some error log time: 11:380pm NZ Time. You can reproduce this error by creating a concept  and save. Open concept and edit and then try to save. It will come up with this new error: This page isn’t working

knowfox.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by oschettler** [comment] 2018-02-12 18:24
I believe that I had an inconsistant composer.lock at that time.
Closed as "can't reproduce". 

Please reopen if problem occurs again.

**Closed as completed by oschettler** 2018-02-12 18:24 UTC
